# Generated by Django 4.2.1 on 2023-05-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_date_created_alter_post_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='files',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to=None),
        ),
    ]
