# Generated by Django 4.2.1 on 2023-05-25 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='files',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to='../data'),
        ),
    ]
